// Code generated by "core generate -add-types"; DO NOT EDIT.

package paginate

import (
	"cogentcore.org/core/types"
)

var _ = types.AddType(&types.Type{Name: "cogentcore.org/core/text/paginate.Options", IDName: "options", Doc: "Options has the parameters for pagination.", Fields: []types.Field{{Name: "PageSize", Doc: "PageSize specifies a standard page size, or Custom."}, {Name: "Units", Doc: "Units are the units in which size is specified.\nWill automatically be set if PageSize != Custom."}, {Name: "Size", Doc: "Size is the size in given units.\nWill automatically be set if PageSize != Custom."}, {Name: "Margins", Doc: "Margins specify the page margins in the size units."}, {Name: "Header", Doc: "Header is the header template string, with #\nreplaced with the page number\n<stretch> adds a stretch element that can be used to accomplish\njustification: at start = right justify, at start and end = center"}, {Name: "Footer", Doc: "Footer is the footer template string, with #\nreplaced with the page number.\n<stretch> adds a stretch element that can be used to accomplish\njustification: at start = right justify, at start and end = center"}}})

var _ = types.AddType(&types.Type{Name: "cogentcore.org/core/text/paginate.pager", IDName: "pager", Doc: "pager implements the pagination.", Fields: []types.Field{{Name: "opts"}, {Name: "ins"}, {Name: "outs"}}})
