// Code generated by 'yaegi extract cogentcore.org/core/base/num'. DO NOT EDIT.

package basesymbols

import (
	"reflect"
)

func init() {
	Symbols["cogentcore.org/core/base/num/num"] = map[string]reflect.Value{}
}
