// Code generated by "stringer -type=Modifiers"; DO NOT EDIT.

package key

import (
	"fmt"
	"strconv"
)

const _Modifiers_name = "ShiftControlAltMetaModifiersN"

var _Modifiers_index = [...]uint8{0, 5, 12, 15, 19, 29}

func (i Modifiers) String() string {
	if i < 0 || i >= Modifiers(len(_Modifiers_index)-1) {
		return "Modifiers(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Modifiers_name[_Modifiers_index[i]:_Modifiers_index[i+1]]
}

func StringToModifiers(s string) (Modifiers, error) {
	for i := 0; i < len(_Modifiers_index)-1; i++ {
		if s == _Modifiers_name[_Modifiers_index[i]:_Modifiers_index[i+1]] {
			return Modifiers(i), nil
		}
	}
	return 0, fmt.Errorf("String %v is not a valid option for type Modifiers", s)
}
