// Code generated by "stringer -type=ActionSignals"; DO NOT EDIT.

package gi

import (
	"fmt"
	"strconv"
)

const _ActionSignals_name = "ActionTriggeredActionSignalsN"

var _ActionSignals_index = [...]uint8{0, 15, 29}

func (i ActionSignals) String() string {
	if i < 0 || i >= ActionSignals(len(_ActionSignals_index)-1) {
		return "ActionSignals(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ActionSignals_name[_ActionSignals_index[i]:_ActionSignals_index[i+1]]
}

func StringToActionSignals(s string) (ActionSignals, error) {
	for i := 0; i < len(_ActionSignals_index)-1; i++ {
		if s == _ActionSignals_name[_ActionSignals_index[i]:_ActionSignals_index[i+1]] {
			return ActionSignals(i), nil
		}
	}
	return 0, fmt.Errorf("String %v is not a valid option for type ActionSignals", s)
}
