// Code generated by "stringer -type=NodeWidgetSignals"; DO NOT EDIT.

package gi

import (
	"fmt"
	"strconv"
)

const _NodeWidgetSignals_name = "NodeSelectedNodeUnselectedNodeOpenedNodeCollapsedNodeWidgetSignalsN"

var _NodeWidgetSignals_index = [...]uint8{0, 12, 26, 36, 49, 67}

func (i NodeWidgetSignals) String() string {
	if i < 0 || i >= NodeWidgetSignals(len(_NodeWidgetSignals_index)-1) {
		return "NodeWidgetSignals(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NodeWidgetSignals_name[_NodeWidgetSignals_index[i]:_NodeWidgetSignals_index[i+1]]
}

func StringToNodeWidgetSignals(s string) (NodeWidgetSignals, error) {
	for i := 0; i < len(_NodeWidgetSignals_index)-1; i++ {
		if s == _NodeWidgetSignals_name[_NodeWidgetSignals_index[i]:_NodeWidgetSignals_index[i+1]] {
			return NodeWidgetSignals(i), nil
		}
	}
	return 0, fmt.Errorf("String %v is not a valid option for type NodeWidgetSignals", s)
}
