// Code generated by "stringer -type=TabWidgetSignals"; DO NOT EDIT.

package gi

import (
	"fmt"
	"strconv"
)

const _TabWidgetSignals_name = "TabSelectedTabUnselectedTabOpenedTabCollapsedTabWidgetSignalsN"

var _TabWidgetSignals_index = [...]uint8{0, 11, 24, 33, 45, 62}

func (i TabWidgetSignals) String() string {
	if i < 0 || i >= TabWidgetSignals(len(_TabWidgetSignals_index)-1) {
		return "TabWidgetSignals(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TabWidgetSignals_name[_TabWidgetSignals_index[i]:_TabWidgetSignals_index[i+1]]
}

func (i *TabWidgetSignals) FromString(s string) error {
	for j := 0; j < len(_TabWidgetSignals_index)-1; j++ {
		if s == _TabWidgetSignals_name[_TabWidgetSignals_index[j]:_TabWidgetSignals_index[j+1]] {
			*i = TabWidgetSignals(j)
			return nil
		}
	}
	return fmt.Errorf("String %v is not a valid option for type TabWidgetSignals", s)
}
