// Code generated by "goki set-version v0.8.12"; DO NOT EDIT.

package colors

const (
	// Version is the version of this package being used
	Version = "v0.8.12"
	// GitCommit is the commit just before the latest version commit
	GitCommit = "120baa5"
	// VersionDate is the date-time of the latest version commit in UTC (in the format 'YYYY-MM-DD HH:MM', which is the Go format '2006-01-02 15:04')
	VersionDate = "2023-09-23 06:42"
)
