// Code generated by "goki version"; DO NOT EDIT.

package grows

const (
	// Version is the version of this package being used
	Version = "v0.3.15"
	// GitCommit is the commit just before the latest version commit
	GitCommit = "24b80e7"
	// VersionDate is the date-time of the latest version commit in UTC (in the format 'YYYY-MM-DD HH:MM', which is the Go format '2006-01-02 15:04')
	VersionDate = "2023-11-14 15:52"
)
