// Code generated by "goki set-version v0.1.0"; DO NOT EDIT.

package main

const (
	// Version is the version of this package being used
	Version = "v0.1.0"
	// GitCommit is the commit just before the latest version commit
	GitCommit = "fdbc47d"
	// VersionDate is the date-time of the latest version commit in UTC (in the format 'YYYY-MM-DD HH:MM', which is the Go format '2006-01-02 15:04')
	VersionDate = "2023-09-21 03:20"
)
