// Code generated by "stringer -type=NodeFlags"; DO NOT EDIT.

package gi3d

import (
	"errors"
	"strconv"
)

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WorldMatrixUpdated-24]
	_ = x[VectorsUpdated-25]
	_ = x[NodeFlagsN-26]
}

const _NodeFlags_name = "WorldMatrixUpdatedVectorsUpdatedNodeFlagsN"

var _NodeFlags_index = [...]uint8{0, 18, 32, 42}

func (i NodeFlags) String() string {
	i -= 24
	if i < 0 || i >= NodeFlags(len(_NodeFlags_index)-1) {
		return "NodeFlags(" + strconv.FormatInt(int64(i+24), 10) + ")"
	}
	return _NodeFlags_name[_NodeFlags_index[i]:_NodeFlags_index[i+1]]
}

func StringToNodeFlags(s string) (NodeFlags, error) {
	for i := 0; i < len(_NodeFlags_index)-1; i++ {
		if s == _NodeFlags_name[_NodeFlags_index[i]:_NodeFlags_index[i+1]] {
			return NodeFlags(i + 24), nil
		}
	}
	return 0, errors.New("String: " + s + " is not a valid option for type: NodeFlags")
}

var _NodeFlags_descMap = map[NodeFlags]string{
	24: `WorldMatrixUpdated means that the Pose.WorldMatrix has been updated`,
	25: `VectorsUpdated means that the rendering vectors information is updated`,
	26: ``,
}

func (i NodeFlags) Desc() string {
	if str, ok := _NodeFlags_descMap[i]; ok {
		return str
	}
	return "NodeFlags(" + strconv.FormatInt(int64(i), 10) + ")"
}
