// Code generated by "stringer -type=FileNodeFlags"; DO NOT EDIT.

package giv

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FileNodeOpen-16]
	_ = x[FileNodeSymLink-17]
	_ = x[FileNodeFlagsN-18]
}

const _FileNodeFlags_name = "FileNodeOpenFileNodeSymLinkFileNodeFlagsN"

var _FileNodeFlags_index = [...]uint8{0, 12, 27, 41}

func (i FileNodeFlags) String() string {
	i -= 16
	if i < 0 || i >= FileNodeFlags(len(_FileNodeFlags_index)-1) {
		return "FileNodeFlags(" + strconv.FormatInt(int64(i+16), 10) + ")"
	}
	return _FileNodeFlags_name[_FileNodeFlags_index[i]:_FileNodeFlags_index[i+1]]
}
