// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package gi

const (
	Version     = "v1.2.5"
	GitCommit   = "f85a0cf" // the commit JUST BEFORE the release
	VersionDate = "2021-03-19 09:08" // UTC
)

