// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package gi

const (
	Version     = "v1.1.1"
	GitCommit   = "7ec4f7a" // the commit JUST BEFORE the release
	VersionDate = "2020-11-24 02:19" // UTC
)

