// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package gi

const (
	Version     = "v1.1.0"
	GitCommit   = "4db973e" // the commit JUST BEFORE the release
	VersionDate = "2020-11-22 11:34" // UTC
)

