// Code generated by "stringer -type=Trilean"; DO NOT EDIT.

package histyle

import (
	"errors"
	"strconv"
)

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Pass-0]
	_ = x[Yes-1]
	_ = x[No-2]
	_ = x[TrileanN-3]
}

const _Trilean_name = "PassYesNoTrileanN"

var _Trilean_index = [...]uint8{0, 4, 7, 9, 17}

func (i Trilean) String() string {
	if i >= Trilean(len(_Trilean_index)-1) {
		return "Trilean(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Trilean_name[_Trilean_index[i]:_Trilean_index[i+1]]
}

func (i *Trilean) FromString(s string) error {
	for j := 0; j < len(_Trilean_index)-1; j++ {
		if s == _Trilean_name[_Trilean_index[j]:_Trilean_index[j+1]] {
			*i = Trilean(j)
			return nil
		}
	}
	return errors.New("String: " + s + " is not a valid option for type: Trilean")
}

var _Trilean_descMap = map[Trilean]string{
	0: ``,
	1: ``,
	2: ``,
	3: ``,
}

func (i Trilean) Desc() string {
	if str, ok := _Trilean_descMap[i]; ok {
		return str
	}
	return "Trilean(" + strconv.FormatInt(int64(i), 10) + ")"
}
