// Code generated by "stringer -type=SamplerModes"; DO NOT EDIT.

package vgpu

import (
	"errors"
	"strconv"
)

var _ = errors.New("dummy error")

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Repeat-0]
	_ = x[MirroredRepeat-1]
	_ = x[ClampToEdge-2]
	_ = x[ClampToBorder-3]
	_ = x[MirrorClampToEdge-4]
	_ = x[SamplerModesN-5]
}

const _SamplerModes_name = "RepeatMirroredRepeatClampToEdgeClampToBorderMirrorClampToEdgeSamplerModesN"

var _SamplerModes_index = [...]uint8{0, 6, 20, 31, 44, 61, 74}

func (i SamplerModes) String() string {
	if i < 0 || i >= SamplerModes(len(_SamplerModes_index)-1) {
		return "SamplerModes(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SamplerModes_name[_SamplerModes_index[i]:_SamplerModes_index[i+1]]
}

func (i *SamplerModes) FromString(s string) error {
	for j := 0; j < len(_SamplerModes_index)-1; j++ {
		if s == _SamplerModes_name[_SamplerModes_index[j]:_SamplerModes_index[j+1]] {
			*i = SamplerModes(j)
			return nil
		}
	}
	return errors.New("String: " + s + " is not a valid option for type: SamplerModes")
}
