// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package vgpu

const (
	Version     = "v1.0.9"
	GitCommit   = "d9ef39f"          // the commit JUST BEFORE the release
	VersionDate = "2023-01-10 07:35" // UTC
)
