// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package vgpu

const (
	Version     = "v1.0.6"
	GitCommit   = "9cf587c"          // the commit JUST BEFORE the release
	VersionDate = "2023-01-05 13:22" // UTC
)
