// Code generated by "stringer -type=Actions"; DO NOT EDIT.

package lex

import (
	"errors"
	"strconv"
)

var _ = errors.New("dummy error")

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Next-0]
	_ = x[Name-1]
	_ = x[Number-2]
	_ = x[Quoted-3]
	_ = x[QuotedRaw-4]
	_ = x[EOL-5]
	_ = x[ReadUntil-6]
	_ = x[PushState-7]
	_ = x[PopState-8]
	_ = x[SetGuestLex-9]
	_ = x[PopGuestLex-10]
	_ = x[ActionsN-11]
}

const _Actions_name = "NextNameNumberQuotedQuotedRawEOLReadUntilPushStatePopStateSetGuestLexPopGuestLexActionsN"

var _Actions_index = [...]uint8{0, 4, 8, 14, 20, 29, 32, 41, 50, 58, 69, 80, 88}

func (i Actions) String() string {
	if i < 0 || i >= Actions(len(_Actions_index)-1) {
		return "Actions(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Actions_name[_Actions_index[i]:_Actions_index[i+1]]
}

func (i *Actions) FromString(s string) error {
	for j := 0; j < len(_Actions_index)-1; j++ {
		if s == _Actions_name[_Actions_index[j]:_Actions_index[j+1]] {
			*i = Actions(j)
			return nil
		}
	}
	return errors.New("String: " + s + " is not a valid option for type: Actions")
}
