// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package pi

const (
	Version     = "v1.0.28"
	GitCommit   = "f257ec4"          // the commit JUST BEFORE the release
	VersionDate = "2023-08-28 00:11" // UTC
)
