// Code generated by "stringer -type=Flags"; DO NOT EDIT.

package ki

import (
	"fmt"
	"strconv"
)

const _Flags_name = "IsFieldUpdatingOnlySelfUpdateNodeAddedNodeCopiedNodeMovedNodeDeletedNodeDestroyedChildAddedChildMovedChildDeletedChildrenDeletedFieldUpdatedPropUpdatedFlagsN"

var _Flags_index = [...]uint8{0, 7, 15, 29, 38, 48, 57, 68, 81, 91, 101, 113, 128, 140, 151, 157}

func (i Flags) String() string {
	if i < 0 || i >= Flags(len(_Flags_index)-1) {
		return "Flags(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Flags_name[_Flags_index[i]:_Flags_index[i+1]]
}

func (i *Flags) FromString(s string) error {
	for j := 0; j < len(_Flags_index)-1; j++ {
		if s == _Flags_name[_Flags_index[j]:_Flags_index[j+1]] {
			*i = Flags(j)
			return nil
		}
	}
	return fmt.Errorf("String %v is not a valid option for type Flags", s)
}
