// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package ki

const (
	Version     = "v1.1.14"
	GitCommit   = "d94e2a0"          // the commit JUST BEFORE the release
	VersionDate = "2023-07-07 18:21" // UTC
)
