// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package ki

const (
	Version     = "v1.1.11"
	GitCommit   = "657f729"          // the commit JUST BEFORE the release
	VersionDate = "2023-01-16 07:19" // UTC
)
