// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package ki

const (
	Version     = "v1.0.7"
	GitCommit   = "38a847d" // the commit JUST BEFORE the release
	VersionDate = "2020-12-27 15:20" // UTC
)

