// Code generated by "core generate"; DO NOT EDIT.

package keyfun

import (
	"cogentcore.org/core/gti"
)

var _ = gti.AddType(&gti.Type{Name: "cogentcore.org/core/keyfun.MapsItem", IDName: "maps-item", Doc: "MapsItem is an entry in a Maps list", Directives: []gti.Directive{{Tool: "gti", Directive: "add", Args: []string{"-setters"}}}, Fields: []gti.Field{{Name: "Name", Doc: "name of keymap"}, {Name: "Desc", Doc: "description of keymap -- good idea to include source it was derived from"}, {Name: "Map", Doc: "to edit key sequence click button and type new key combination; to edit function mapped to key sequence choose from menu"}}})

// SetName sets the [MapsItem.Name]:
// name of keymap
func (t *MapsItem) SetName(v string) *MapsItem { t.Name = v; return t }

// SetDesc sets the [MapsItem.Desc]:
// description of keymap -- good idea to include source it was derived from
func (t *MapsItem) SetDesc(v string) *MapsItem { t.Desc = v; return t }

// SetMap sets the [MapsItem.Map]:
// to edit key sequence click button and type new key combination; to edit function mapped to key sequence choose from menu
func (t *MapsItem) SetMap(v Map) *MapsItem { t.Map = v; return t }
