// Code generated by "core generate -add-types"; DO NOT EDIT.

package timer

import (
	"cogentcore.org/core/types"
)

var _ = types.AddType(&types.Type{Name: "cogentcore.org/core/base/timer.Time", IDName: "time", Doc: "Time manages the timer accumulated time and count", Fields: []types.Field{{Name: "St", Doc: "the most recent starting time"}, {Name: "Total", Doc: "the total accumulated time"}, {Name: "N", Doc: "the number of start/stops"}}})
