// Code generated by "stringer -type=Cross"; DO NOT EDIT.

package lifecycle

import (
	"fmt"
	"strconv"
)

const _Cross_name = "CrossNoneCrossOnCrossOffCrossN"

var _Cross_index = [...]uint8{0, 9, 16, 24, 30}

func (i Cross) String() string {
	if i >= Cross(len(_Cross_index)-1) {
		return "Cross(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Cross_name[_Cross_index[i]:_Cross_index[i+1]]
}

func StringToCross(s string) (Cross, error) {
	for i := 0; i < len(_Cross_index)-1; i++ {
		if s == _Cross_name[_Cross_index[i]:_Cross_index[i+1]] {
			return Cross(i), nil
		}
	}
	return 0, fmt.Errorf("String %v is not a valid option for type Cross", s)
}
